Fix release-only script error (#11)
Add release build to CI workflow.
Replace `Spec.factory` with `Spec.object_class`. This is a better API
even if the original solution worked in release.

Fixes error:
```
 SCRIPT ERROR: Parse Error: Cannot find member "new" in base "_TestSimpleObj".
          at: GDScript::reload (res://scripts/util/gdserde.gd:419)
```

diff --git a/scripts/test-headless b/scripts/test-headless
--- a/scripts/test-headless
+++ b/scripts/test-headless
@@ -119,3 +119,7 @@ if echo "$output" | grep -q "^SCRIPT ERROR:"; then
     error "Failed: Script error"
     exit 1
 fi
+if echo "$output" | grep -q "^ERROR:"; then
+    error "Failed: Error"
+    exit 1
+fi
